### ISSUE TITLE
Add an option to provide what is the goal of the function in decorator parameters

### ISSUE THREAD

**Issue by Pallavi-Sinha-12** [Pallavi-Sinha-12/bitefix#1]
### Description
As a user of BiteFix, I find that adding a description or function goal to the decorators could enhance the usability and understanding of the decorated functions. This will provide more context to the AI Agents and improve the quality of suggestions.

### Tasks
- [ ] Modify the decorator implementation to accept a `decorated_function_goal` parameter.
- [ ] Ensure that the `decorated_function_goal` parameter is stored and accessible during the debugging process.
- [ ] Update AI Agents' prompts to consider the provided `decorated_function_goal` in their suggestions.

**Comment by Pallavi-Sinha-12** [comment]
This issue is fixed and closed
